#springdoc.swagger-ui.path:/swagger-doc/swagger-ui.html
#springdoc.api-docs.path:/swagger-doc/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    path: /swagger-doc/v3/api-docs

topic:
  name: t.food.order

spring:
  kafka:
    consumer:
      group-id: "default"